services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: kazouinventory_server:local
    container_name: kazouinventory_server
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=cp7JhZO-xG69nHnRHYxU5LrUSoMcNwXFhz2kO6IWwCs
    ports:
      - "5000:5000"

volumes:
  db_data: {}
